services:
  sqbkp:
    image: registry.stackbleed.net/sqbkp:latest
    environment:
      REMOTE: ${REMOTE}
      REMOTE_PATH: ${REMOTE_PATH}
      TZ: ${TIME_ZONE} 
    volumes:
      - ${SSH_DIRECTORY}:/home/appuser/.ssh:ro
      - ${BACKUP_DIRECTORY}:/backup
